[build]
publish = "public"
command = "hugo --gc"

# [[redirects]]
#   from = "https://rand.netlify.com/post/*"
#   to = "https://ricardoanderegg.com/posts/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://rand.netlify.app/post/*"
#   to = "https://ricardoanderegg.com/posts/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://ricardoanderegg.com/post/*"
#   to = "https://ricardoanderegg.com/posts/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://rand.netlify.com/*"
#   to = "https://ricardoanderegg.com/:splat"
#   status = 301
#   force = true

# [[redirects]]
#   from = "https://rand.netlify.app/*"
#   to = "https://ricardoanderegg.com/:splat"
#   status = 301
#   force = true


[[redirects]]
    from = "/posts/python_mamba_pip_tools/"
    to = "/posts/python-manage-environments-with-mamba-pip-tools/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/single_file_apps/"
    to = "/posts/write-apps-in-single-file/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/notes_simple_made_easy/"
    to = "/posts/notes-simple-made-easy-rich-hickey/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/bash_wrap_functions/"
    to = "/posts/wrap-bash-code-functions/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/conda_management/"
    to = "/posts/python-manage-conda-environments/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/fixing_ghcup_bug/"
    to = "/posts/fixing-ghcup-bug/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/divide_search_abstract/"
    to = "/posts/problem-solving-divide-search-abstract/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/langid_fasttext/"
    to = "/posts/python-fast-language-identification-fasttext/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/notebook_linking/"
    to = "/posts/python-jupyter-link-local-notebook/"
    status = 303
    force = false
[[redirects]]
    from = "/posts/black_jupyter/"
    to = "/posts/black-formatting-jupyter-notebook/"
    status = 303
    force = false

[[redirects]]
    from = "/thoughts/short_posts/"
    to = "/thoughts/write-short-blog-posts/"
    status = 303
    force = false
[[redirects]]
    from = "/thoughts/education_before_innovation/"
    to = "/thoughts/education-before-innovation/"
    status = 303
    force = false

[[redirects]]
    from = "/recipes/remote_docker_control_ssh/"
    to = "/recipes/remote-manage-docker-with-ssh/"
    status = 303
    force = false
[[redirects]]
    from = "/recipes/secure_docker_root_local_files/"
    to = "/recipes/local-files-permissions-docker-non-root-security/"
    status = 303
    force = false
[[redirects]]
    from = "/recipes/langid_fasttext/"
    to = "/recipes/python-fast-language-identification-fasttext/"
    status = 303
    force = false


# [[redirects]]
#   from = "/post/*"
#   to = "/posts/:splat"
